version: "3.9"

services:
  rooms-database:
    image: postgres
    container_name: rooms-database
    restart: always
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rooms-database
    ports:
      - "5432:5432"
  rooms-database-migrations:
    image: migrate/migrate
    container_name: rooms-database-migrations
    restart: on-failure
    depends_on:
      - rooms-database
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./migrations:/migrations
    entrypoint: []
    command: /wait-for-it.sh rooms-database:5432 -- migrate -path=/migrations/ -database postgres://postgres:postgres@rooms-database:5432/rooms-database?sslmode=disable up
  server:
    build: ./
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - DSN="host=rooms-database user=postgres password=postgres dbname=postgres-test port=5432 sslmode=disable"
      - JWT_SECRET="test-secret"
      - HTTP_SERVER_ADDRESS="http://0.0.0.0:8080"
      - APP_ENV=development
    depends_on:
      - rooms-database